import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import {
  registerAppTool,
  registerAppResource,
  RESOURCE_MIME_TYPE,
} from '@modelcontextprotocol/ext-apps/server'
import { z } from 'zod'
import { config } from './config.js'
import { audioRepo, usageRepo, prefsRepo } from './db.js'
import { putAudio, presignAudioUrl, deleteAudioObject } from './storage.js'
import {
  synthesize,
  resolveVoice,
  chunkText,
  estimateSec,
  VOICES,
  FISH_VOICES,
  providerForVoice,
} from './tts.js'
import type { TtsProvider } from './tts.js'
import { startGenerationJob } from './jobs.js'
import { userIdFrom, authUserFrom } from './auth.js'
import { ensureSlug } from './share.js'
import type {
  AudioRecord,
  HistoryItem,
  HistoryPayload,
  PlayerPayload,
  ProcessingPayload,
  StatusPayload,
  VortexPayload,
} from './types.js'

const PLAYER_URI = 'ui://oto/player.html'

// Texts at or under SYNC_THRESHOLD synthesize inside the tool call (well under
// host/edge timeouts); longer ones return a processing payload and generate in
// a background job that the widget polls via get_audio_status.
const SYNC_THRESHOLD = 4_000
const TEXT_MAX_CHARS = 50_000

// Railway buckets use virtual-host style URLs: presigned GETs resolve to
// https://<bucket>.<endpoint-host>/..., so the CSP must cover that subdomain,
// not just the bare endpoint origin.
const endpointUrl = new URL(config.BUCKET_ENDPOINT)
const bucketOrigins = [
  endpointUrl.origin,
  `${endpointUrl.protocol}//${config.BUCKET_NAME}.${endpointUrl.host}`,
]

// The iframe CSP is deny-by-default; the player streams mp3s from the bucket.
const uiCsp = {
  csp: {
    resourceDomains: bucketOrigins,
    connectDomains: bucketOrigins,
  },
  prefersBorder: true,
}

let playerHtml: string | null = null
function loadPlayerHtml(): string {
  if (playerHtml === null) {
    const htmlPath = path.join(process.cwd(), 'dist', 'ui', 'index.html')
    try {
      playerHtml = readFileSync(htmlPath, 'utf-8')
    } catch {
      throw new Error(`Player UI bundle missing at ${htmlPath} — run "npm run build:ui" first`)
    }
  }
  return playerHtml
}

const playerPayloadShape = {
  kind: z.literal('audio'),
  id: z.string(),
  title: z.string(),
  audioUrl: z.string(),
  durationSec: z.number().nullable(),
  voice: z.string(),
  createdAt: z.string(),
  summary: z.string().nullable(),
  emoji: z.string().nullable(),
  mood: z.string().nullable(),
  deduped: z.boolean(),
}

const audioStatusEnum = z.enum(['processing', 'ready', 'error'])

const statusPayloadShape = {
  kind: z.literal('status'),
  id: z.string(),
  status: audioStatusEnum,
  chunksDone: z.number(),
  chunksTotal: z.number(),
  error: z.string().nullable(),
  audio: z.object(playerPayloadShape).nullable(),
}

const historyPayloadShape = {
  kind: z.literal('history'),
  items: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      durationSec: z.number().nullable(),
      voice: z.string(),
      charCount: z.number(),
      createdAt: z.string(),
      status: audioStatusEnum,
      summary: z.string().nullable(),
      emoji: z.string().nullable(),
      mood: z.string().nullable(),
    }),
  ),
  total: z.number(),
}

/** Trim an optional string; empty (or absent) becomes null. */
function cleanStr(v: string | undefined): string | null {
  const t = v?.trim()
  return t ? t : null
}

function makeTitle(text: string): string {
  const line = text.replace(/\s+/g, ' ').trim()
  return line.length <= 60 ? line : `${line.slice(0, 57)}…`
}

/** Prefer a title the caller (Claude) supplies; fall back to the text snippet. */
function resolveTitle(provided: string | undefined, text: string): string {
  const t = provided?.replace(/\s+/g, ' ').trim()
  if (!t) return makeTitle(text)
  return t.length <= 80 ? t : `${t.slice(0, 77)}…`
}

function contentHash(text: string, voice: string, model: string, instructions?: string): string {
  // The instructions suffix is only appended when present so hashes (and the
  // stored audio they dedup against) stay stable for instruction-less requests.
  // Keyed by the resolved model, so switching provider (openai vs fish) never
  // dedups against audio generated by the other one.
  const key =
    `${model}|${voice}|${config.TTS_FORMAT}|${text}` +
    (instructions ? `|i:${instructions}` : '')
  return createHash('sha256').update(key).digest('hex')
}

function fmtDuration(durationSec: number | null): string {
  if (durationSec === null) return 'unknown length'
  const s = Math.round(durationSec)
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

const quotaSec = config.QUOTA_MINUTES * 60

function fmtMinutes(seconds: number): string {
  return `${(seconds / 60).toFixed(1)} min`
}

/** Exempt from the generation quota via env allowlist or the DB unlimited flag. */
async function isQuotaExempt(userId: string, email?: string): Promise<boolean> {
  if (email && config.quotaExemptEmails.has(email.toLowerCase())) return true
  return usageRepo.isUnlimited(userId)
}

async function playerPayload(rec: AudioRecord, deduped: boolean): Promise<PlayerPayload> {
  return {
    kind: 'audio',
    id: rec.id,
    title: rec.title,
    audioUrl: await presignAudioUrl(rec.objectKey),
    durationSec: rec.durationSec,
    voice: rec.voice,
    createdAt: rec.createdAt,
    summary: rec.summary,
    emoji: rec.emoji,
    mood: rec.mood,
    deduped,
  }
}

function processingPayload(rec: AudioRecord): ProcessingPayload {
  return {
    kind: 'processing',
    id: rec.id,
    title: rec.title,
    charCount: rec.charCount,
    chunksDone: rec.chunksDone,
    // chunksTotal is always set on 'processing' rows; ?? 0 satisfies the type.
    chunksTotal: rec.chunksTotal ?? 0,
    createdAt: rec.createdAt,
  }
}

function historyItem(rec: AudioRecord): HistoryItem {
  return {
    id: rec.id,
    title: rec.title,
    durationSec: rec.durationSec,
    voice: rec.voice,
    charCount: rec.charCount,
    createdAt: rec.createdAt,
    status: rec.status,
    summary: rec.summary,
    emoji: rec.emoji,
    mood: rec.mood,
  }
}

type ToolExtra = { authInfo?: Parameters<typeof userIdFrom>[0]['authInfo'] }

function errorResult(err: unknown) {
  const message = err instanceof Error ? err.message : String(err)
  return { content: [{ type: 'text' as const, text: `Error: ${message}` }], isError: true }
}

async function getHistory(userId: string, limit?: number, offset?: number) {
  const { items, total } = await audioRepo.listByUser(userId, limit, offset)
  const payload: HistoryPayload = { kind: 'history', items: items.map(historyItem), total }
  return {
    content: [
      {
        type: 'text' as const,
        text: total === 0
          ? 'No audios generated yet.'
          : `${total} audio${total === 1 ? '' : 's'} in history. The list is displayed to the user.`,
      },
    ],
    structuredContent: payload,
  }
}

export function buildServer(): McpServer {
  const origin = new URL(config.MCP_SERVER_URL).origin
  const server = new McpServer({
    name: 'oto',
    title: 'oto',
    version: '0.1.0',
    websiteUrl: origin,
    icons: [{ src: `${origin}/icon.png`, mimeType: 'image/png', sizes: ['512x512'] }],
  })

  registerAppResource(
    server,
    'oto player',
    PLAYER_URI,
    { _meta: { ui: uiCsp } },
    async () => ({
      contents: [
        {
          uri: PLAYER_URI,
          mimeType: RESOURCE_MIME_TYPE,
          text: loadPlayerHtml(),
          // Content-item _meta takes precedence over the listing-level default.
          _meta: { ui: uiCsp },
        },
      ],
    }),
  )

  registerAppTool(
    server,
    'text_to_speech',
    {
      title: 'Text to speech',
      description:
        'Convert text to spoken audio and show an inline audio player. ' +
        'Audio is generated once and stored: repeating the same text/voice returns the existing audio. ' +
        `Texts over ${SYNC_THRESHOLD} characters generate in the background — the player shows progress and updates itself when ready. ` +
        `Voices: ${[...VOICES, ...(config.fishEnabled ? Object.keys(FISH_VOICES) : [])].join(', ')}.` +
        (quotaSec > 0
          ? ` Each user can generate up to ${config.QUOTA_MINUTES} minutes of new audio; stored audios stay playable for free.`
          : ''),
      inputSchema: {
        // Long texts generate in the background, so the cap bounds per-request
        // cost rather than response latency.
        text: z.string().min(1).max(TEXT_MAX_CHARS).describe('The text to read aloud'),
        voice: z.string().optional().describe(`Voice to use (default ${config.TTS_VOICE})`),
        instructions: z
          .string()
          .max(4000)
          .optional()
          .describe('Optional delivery directions: tone, accent, emotion, pacing'),
        title: z
          .string()
          .max(80)
          .optional()
          .describe('A short, human-friendly title for this audio (a few words). If omitted, the start of the text is used.'),
        summary: z
          .string()
          .max(280)
          .optional()
          .describe('A one-line synopsis of the audio, shown as the player/list subtitle.'),
        emoji: z
          .string()
          .max(8)
          .optional()
          .describe('A single emoji that represents this audio.'),
        language: z
          .string()
          .max(40)
          .optional()
          .describe('The detected language of the source text (e.g. "Spanish" or "es").'),
        mood: z
          .string()
          .max(30)
          .optional()
          .describe('A one-word mood used to tint the generative cover: e.g. "calm", "energetic", "serious", "playful", "warm".'),
        tags: z
          .array(z.string().max(30))
          .max(6)
          .optional()
          .describe('Up to 6 short topic tags for this audio.'),
      },
      // No outputSchema: the result is a union (PlayerPayload | ProcessingPayload)
      // that a flat zod shape can't express; structuredContent alone is valid.
      _meta: { ui: { resourceUri: PLAYER_URI } },
    },
    async ({ text, voice, instructions, title, summary, emoji, language, mood, tags }, extra) => {
      try {
        const { userId, email } = authUserFrom(extra as ToolExtra)
        const cleanText = text.trim()
        if (!cleanText) return errorResult(new Error('Text is empty'))

        // Metadata only — never folded into contentHash, so dedup is unaffected.
        const meta = {
          summary: cleanStr(summary),
          emoji: cleanStr(emoji),
          language: cleanStr(language),
          mood: cleanStr(mood),
          tags: (tags ?? []).map((t) => t.trim()).filter(Boolean),
        }

        // User prefs fill in what the request leaves unspecified: pref voice
        // when no voice arg. The provider is implied by the resolved voice.
        const prefs = await prefsRepo.get(userId)
        // Pref language fills in missing language metadata (display-only).
        meta.language ??= prefs.language
        const resolvedVoice = resolveVoice(voice ?? prefs.voice ?? undefined)
        const provider: TtsProvider =
          providerForVoice(resolvedVoice) === 'fish' ? 'fish' : config.TTS_PROVIDER
        const model = provider === 'fish' ? config.FISH_MODEL : config.TTS_MODEL
        const hash = contentHash(cleanText, resolvedVoice, model, instructions?.trim() || undefined)

        let existing = await audioRepo.findByHash(userId, hash)
        // Janitor here as well as in get_audio_status: a wedged 'processing'
        // row must not hold its dedup key forever when the widget never polls
        // it to resolution (it flips to 'error' and is cleared just below).
        if (existing) existing = await audioRepo.resolveStale(existing)
        if (existing?.status === 'processing') {
          return {
            content: [
              {
                type: 'text' as const,
                text: `"${existing.title}" is already generating (${existing.chunksDone}/${existing.chunksTotal ?? '?'} chunks done) — the player updates itself when ready.`,
              },
            ],
            structuredContent: processingPayload(existing),
          }
        }
        if (existing?.status === 'error') {
          // A dead row would block the dedup key forever — clear it and regenerate.
          await audioRepo.deleteById(userId, existing.id)
        } else if (existing) {
          const payload = await playerPayload(existing, true)
          return {
            content: [
              {
                type: 'text' as const,
                text: `Reused existing audio "${existing.title}" (${fmtDuration(existing.durationSec)}, voice ${existing.voice}) — no regeneration needed. The player is displayed to the user.`,
              },
            ],
            structuredContent: payload,
          }
        }

        const exempt = quotaSec === 0 || (await isQuotaExempt(userId, email))
        if (quotaSec > 0 && !exempt) {
          const usedSec = await usageRepo.generatedSec(userId)
          if (usedSec >= quotaSec) {
            return errorResult(
              new Error(
                `Generation limit reached (${fmtMinutes(usedSec)} of ${config.QUOTA_MINUTES} min). ` +
                  'New audio cannot be generated, but everything in your history stays playable. ' +
                  `Upgrade for unlimited generation: ${config.UPGRADE_URL}`,
              ),
            )
          }
          // Pre-flight on the length estimate (with 15% headroom for its
          // roughness) so a long text can't start a background job that blows
          // far past the quota.
          const estSec = estimateSec(cleanText.length)
          if (usedSec + estSec > quotaSec * 1.15) {
            return errorResult(
              new Error(
                `This text is ~${fmtMinutes(estSec)} of audio, but only ${fmtMinutes(Math.max(quotaSec - usedSec, 0))} ` +
                  `of the ${config.QUOTA_MINUTES} min generation quota remains. Try a shorter text.`,
              ),
            )
          }
        }

        const objectKey = `audio/${userId}/${hash}.${config.TTS_FORMAT}`

        if (cleanText.length > SYNC_THRESHOLD) {
          const chunks = chunkText(cleanText)
          const { rec, created } = await audioRepo.insert({
            userId,
            textHash: hash,
            text: cleanText,
            title: resolveTitle(title, cleanText),
            ...meta,
            voice: resolvedVoice,
            model,
            format: config.TTS_FORMAT,
            objectKey,
            durationSec: null,
            charCount: cleanText.length,
            status: 'processing',
            chunksTotal: chunks.length,
            chunksDone: 0,
            errorMessage: null,
          })
          // Short-link slug at creation; a failure must never fail generation.
          await ensureSlug(rec).catch(() => {})
          // Only the request that actually inserted the row owns the job —
          // a lost race means another request is already generating it.
          if (created) {
            startGenerationJob({
              recId: rec.id,
              userId,
              email,
              text: cleanText,
              voice: resolvedVoice,
              instructions,
              provider,
              objectKey: rec.objectKey,
            })
          }
          if (rec.status === 'ready') {
            return {
              content: [
                { type: 'text' as const, text: `Audio "${rec.title}" already exists. The player is displayed to the user.` },
              ],
              structuredContent: await playerPayload(rec, true),
            }
          }
          return {
            content: [
              {
                type: 'text' as const,
                text: `Generating ~${fmtMinutes(estimateSec(cleanText.length))} of audio in the background — the player updates itself when ready.`,
              },
            ],
            structuredContent: processingPayload(rec),
          }
        }

        const result = await synthesize(cleanText, { voice: resolvedVoice, instructions, provider })
        await putAudio(objectKey, result.audio)

        const { rec } = await audioRepo.insert({
          userId,
          textHash: hash,
          text: cleanText,
          title: resolveTitle(title, cleanText),
          ...meta,
          voice: result.voice,
          model: result.model,
          format: result.format,
          objectKey,
          durationSec: result.durationSec,
          charCount: result.charCount,
          status: 'ready',
          chunksTotal: null,
          chunksDone: 0,
          errorMessage: null,
        })
        // Short-link slug at creation; a failure must never fail generation.
        await ensureSlug(rec).catch(() => {})

        // Usage is recorded for everyone (cost visibility); only non-exempt
        // users see — and are bound by — the quota.
        const generatedSec = result.durationSec ?? estimateSec(result.charCount)
        await usageRepo.addGeneratedSec(userId, generatedSec, email)
        let quotaNote = ''
        if (quotaSec > 0 && !exempt) {
          const usedSec = await usageRepo.generatedSec(userId)
          quotaNote = ` Generation quota used: ${fmtMinutes(usedSec)} of ${config.QUOTA_MINUTES} min.`
        }

        const payload = await playerPayload(rec, false)
        return {
          content: [
            {
              type: 'text' as const,
              text: `Generated audio "${rec.title}" (${fmtDuration(rec.durationSec)}, voice ${rec.voice}). The player is displayed to the user.${quotaNote}`,
            },
          ],
          structuredContent: payload,
        }
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  registerAppTool(
    server,
    'list_history',
    {
      title: 'Audio history',
      description: "List the user's previously generated audios and show the history browser.",
      inputSchema: {
        limit: z.number().int().min(1).max(200).optional().describe('Page size (default 50)'),
        offset: z.number().int().min(0).optional().describe('Pagination offset'),
      },
      outputSchema: historyPayloadShape,
      _meta: { ui: { resourceUri: PLAYER_URI } },
    },
    async ({ limit, offset }, extra) => {
      try {
        return await getHistory(userIdFrom(extra as ToolExtra), limit, offset)
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  registerAppTool(
    server,
    'vortex',
    {
      title: 'The Vortex',
      description:
        'Easter egg: open the oto vortex — a hypnotic ASCII spiral visual. ' +
        'Call when the user asks for the vortex, trip mode, or the oto easter egg. ' +
        'Generates no audio and costs nothing.',
      inputSchema: {},
      outputSchema: { kind: z.literal('vortex'), seed: z.number() },
      annotations: { readOnlyHint: true },
      _meta: { ui: { resourceUri: PLAYER_URI } },
    },
    async (_args, extra) => {
      try {
        userIdFrom(extra as ToolExtra)
        const payload: VortexPayload = {
          kind: 'vortex',
          seed: Math.floor(Math.random() * 2 ** 31),
        }
        return {
          content: [
            {
              type: 'text' as const,
              text: 'The vortex is open. Best enjoyed while audio plays. There is nothing else to say.',
            },
          ],
          structuredContent: payload,
        }
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  // App-only tools: callable from the player iframe, hidden from the model.
  registerAppTool(
    server,
    'get_history',
    {
      description: 'Fetch a page of audio history (app-internal).',
      inputSchema: {
        limit: z.number().int().min(1).max(200).optional(),
        offset: z.number().int().min(0).optional(),
      },
      outputSchema: historyPayloadShape,
      _meta: { ui: { resourceUri: PLAYER_URI, visibility: ['app'] } },
    },
    async ({ limit, offset }, extra) => {
      try {
        return await getHistory(userIdFrom(extra as ToolExtra), limit, offset)
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  registerAppTool(
    server,
    'get_audio_url',
    {
      description: 'Get a fresh playback URL for a stored audio (app-internal).',
      inputSchema: { id: z.string().describe('Audio id') },
      outputSchema: playerPayloadShape,
      _meta: { ui: { resourceUri: PLAYER_URI, visibility: ['app'] } },
    },
    async ({ id }, extra) => {
      try {
        const userId = userIdFrom(extra as ToolExtra)
        const rec = await audioRepo.getById(userId, id)
        if (!rec) return errorResult(new Error('Audio not found'))
        if (rec.status !== 'ready') return errorResult(new Error('Audio not ready'))
        const payload = await playerPayload(rec, true)
        return {
          content: [{ type: 'text' as const, text: `Playback URL refreshed for "${rec.title}".` }],
          structuredContent: payload,
        }
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  registerAppTool(
    server,
    'get_audio_status',
    {
      description: 'Check generation progress for an audio (app-internal, polled by the player).',
      inputSchema: { id: z.string().describe('Audio id') },
      outputSchema: statusPayloadShape,
      annotations: { readOnlyHint: true },
      _meta: { ui: { resourceUri: PLAYER_URI, visibility: ['app'] } },
    },
    async ({ id }, extra) => {
      try {
        const userId = userIdFrom(extra as ToolExtra)
        let rec = await audioRepo.getById(userId, id)
        if (!rec) return errorResult(new Error('Audio not found'))
        // Lazy janitor: flips generations stuck in 'processing' to 'error'.
        rec = await audioRepo.resolveStale(rec)
        const payload: StatusPayload = {
          kind: 'status',
          id: rec.id,
          status: rec.status,
          chunksDone: rec.chunksDone,
          chunksTotal: rec.chunksTotal ?? 0,
          error: rec.errorMessage,
          audio: rec.status === 'ready' ? await playerPayload(rec, false) : null,
        }
        return {
          content: [{ type: 'text' as const, text: `"${rec.title}" is ${rec.status}.` }],
          structuredContent: payload,
        }
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  registerAppTool(
    server,
    'delete_audio',
    {
      description: 'Delete a stored audio and its file (app-internal).',
      inputSchema: { id: z.string().describe('Audio id') },
      outputSchema: { ok: z.boolean(), id: z.string() },
      // Hosts without MCP Apps support ignore visibility:["app"] and expose
      // this to the model — the destructive hint lets them gate it.
      annotations: { destructiveHint: true },
      _meta: { ui: { resourceUri: PLAYER_URI, visibility: ['app'] } },
    },
    async ({ id }, extra) => {
      try {
        const userId = userIdFrom(extra as ToolExtra)
        const rec = await audioRepo.deleteById(userId, id)
        if (!rec) return errorResult(new Error('Audio not found'))
        try {
          await deleteAudioObject(rec.objectKey)
        } catch (err) {
          // Row is gone; an orphaned object is acceptable. Surface in logs only.
          console.error(`Failed to delete bucket object ${rec.objectKey}:`, err)
        }
        return {
          content: [{ type: 'text' as const, text: `Deleted "${rec.title}".` }],
          structuredContent: { ok: true, id },
        }
      } catch (err) {
        return errorResult(err)
      }
    },
  )

  return server
}
